[package]
name = "uefi-loader"
version = "0.1.0"
edition = "2024"


[dependencies]
log = "0.4.29"
uefi = { version = "0.36.1", features = ["panic_handler", "logger"] }
uefi-raw = "0.13.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
